#!/usr/bin/env python
"""
Train the Widar3.0 gesture/motion classifier on BVP cubes generated by run_pipeline.py.
This is a light refactor of the official widar3_keras.py with CLI and cleaner preprocessing.
"""
from __future__ import annotations

import argparse
import glob
import os
import sys
from pathlib import Path

import numpy as np
import scipy.io as scio
import tensorflow as tf
from sklearn.model_selection import train_test_split
from tensorflow import keras
from tensorflow.keras import layers


def normalize_data(data_1: np.ndarray) -> np.ndarray:
    data_1_max = np.concatenate((data_1.max(axis=0), data_1.max(axis=1)), axis=0).max(axis=0)
    data_1_min = np.concatenate((data_1.min(axis=0), data_1.min(axis=1)), axis=0).min(axis=0)
    if np.any((data_1_max - data_1_min) == 0):
        return data_1
    data_1_max_rep = np.tile(data_1_max, (data_1.shape[0], data_1.shape[1], 1))
    data_1_min_rep = np.tile(data_1_min, (data_1.shape[0], data_1.shape[1], 1))
    return (data_1 - data_1_min_rep) / (data_1_max_rep - data_1_min_rep)


def zero_padding(data, T_MAX):
    data_pad = []
    for sample in data:
        t = np.array(sample).shape[2]
        data_pad.append(np.pad(sample, ((0, 0), (0, 0), (T_MAX - t, 0)), "constant", constant_values=0).tolist())
    return np.array(data_pad)


def onehot_encoding(label, num_class):
    label = np.array(label).astype("int32")
    label = np.squeeze(label)
    return np.eye(num_class)[label - 1]


def load_data(path_to_data: Path, motion_sel):
    T_MAX = 0
    data, label = [], []
    for file_path in glob.glob(str(path_to_data / "*.npz")) + glob.glob(str(path_to_data / "*.mat")):
        try:
            if file_path.endswith(".npz"):
                mat = np.load(file_path)
                data_1 = mat["velocity_spectrum_ro"]
            else:
                mat = scio.loadmat(file_path)
                data_1 = mat["velocity_spectrum_ro"]

            label_1 = int(Path(file_path).stem.split("-")[1])
            location = int(Path(file_path).stem.split("-")[2])
            orientation = int(Path(file_path).stem.split("-")[3])
            repetition = int(Path(file_path).stem.split("-")[4])

            if label_1 not in motion_sel:
                continue

            data_normed_1 = normalize_data(data_1)
            T_MAX = max(T_MAX, np.array(data_1).shape[2])
        except Exception:
            continue

        data.append(data_normed_1.tolist())
        label.append(label_1)

    data = zero_padding(data, T_MAX)
    data = np.swapaxes(np.swapaxes(data, 1, 3), 2, 3)  # [N,20,20',T_MAX]=>[N,T_MAX,20,20']
    data = np.expand_dims(data, axis=-1)  # [N,T_MAX,20,20]=>[N,T_MAX,20,20,1]
    label = np.array(label)
    return data, label


def assemble_model(input_shape, n_class, dropout=0.5, n_gru_hidden_units=128, learning_rate=1e-3):
    model_input = layers.Input(shape=input_shape, dtype="float32", name="name_model_input")
    x = layers.TimeDistributed(layers.Conv2D(16, kernel_size=(5, 5), activation="relu", data_format="channels_last"))(
        model_input
    )
    x = layers.TimeDistributed(layers.MaxPooling2D(pool_size=(2, 2)))(x)
    x = layers.TimeDistributed(layers.Flatten())(x)
    x = layers.TimeDistributed(layers.Dense(64, activation="relu"))(x)
    x = layers.TimeDistributed(layers.Dropout(dropout))(x)
    x = layers.TimeDistributed(layers.Dense(64, activation="relu"))(x)
    x = layers.GRU(n_gru_hidden_units, return_sequences=False)(x)
    x = layers.Dropout(dropout)(x)
    model_output = layers.Dense(n_class, activation="softmax", name="name_model_output")(x)

    model = keras.Model(inputs=model_input, outputs=model_output)
    model.compile(optimizer=keras.optimizers.RMSprop(learning_rate=learning_rate), loss="categorical_crossentropy", metrics=["accuracy"])
    return model


def parse_args():
    parser = argparse.ArgumentParser(description="Train Widar3.0 classifier on BVP data.")
    parser.add_argument("--data-dir", default="python_pipeline/output", help="Folder containing *_bvp.npz or .mat files")
    parser.add_argument("--motions", default="1,2,3,4,5,6", help="Comma-separated motion IDs to include")
    parser.add_argument("--gpu", default=None, help="GPU id (e.g., 0 or 1). Leave unset for CPU.")
    parser.add_argument("--epochs", type=int, default=30)
    parser.add_argument("--batch-size", type=int, default=32)
    parser.add_argument("--dropout", type=float, default=0.5)
    parser.add_argument("--learning-rate", type=float, default=1e-3)
    parser.add_argument("--use-existing", action="store_true", help="Load model_widar3_trained.h5 if present")
    parser.add_argument("--model-path", default="model_widar3_trained.h5")
    return parser.parse_args()


def main():
    args = parse_args()
    if args.gpu is not None:
        os.environ["CUDA_VISIBLE_DEVICES"] = args.gpu
        tf.random.set_seed(1)
    else:
        os.environ["CUDA_VISIBLE_DEVICES"] = ""

    ALL_MOTION = [int(m) for m in args.motions.split(",") if m]
    N_MOTION = len(ALL_MOTION)

    data, label = load_data(Path(args.data_dir), ALL_MOTION)
    if data.shape[0] == 0:
        print("No samples found in", args.data_dir)
        sys.exit(1)
    print(f"Loaded {label.shape[0]} samples with shape {data[0].shape}")

    data_train, data_test, label_train, label_test = train_test_split(data, label, test_size=0.1, stratify=label)
    label_train_1h = onehot_encoding(label_train, N_MOTION)

    if args.use_existing and Path(args.model_path).exists():
        model = keras.models.load_model(args.model_path)
    else:
        model = assemble_model(
            input_shape=(data.shape[1], data.shape[2], data.shape[3], data.shape[4]),
            n_class=N_MOTION,
            dropout=args.dropout,
            learning_rate=args.learning_rate,
        )
        model.fit(
            {"name_model_input": data_train},
            {"name_model_output": label_train_1h},
            batch_size=args.batch_size,
            epochs=args.epochs,
            verbose=1,
            validation_split=0.1,
            shuffle=True,
        )
        model.save(args.model_path)

    print("Testing...")
    label_test_pred = model.predict(data_test, verbose=0)
    label_test_pred = np.argmax(label_test_pred, axis=-1) + 1
    acc = np.mean(label_test_pred == label_test)
    print("Test accuracy:", acc)


if __name__ == "__main__":
    main()
